#!/bin/sh
[ -e /run/nginx/nginx.pid ]  && /usr/sbin/nginx -s stop

/usr/sbin/nginx && \
certbot certonly --text --agree-tos --webroot -w /var/lib/nginx/html --register-unsafely-without-email -d $SECURE_DOMAIN_NAME && \
confd -onetime -backend env
/usr/sbin/nginx -s reload && \
$@